class SolvedError(Exception):
    pass


class CalculateFailedError(SolvedError):
    pass
